### ISSUE TITLE
TypeError: `connect` only accepts a callback

### ISSUE THREAD

**Issue by archmangler** [sgnn7/deploying_with_docker#2]
I'm following along with the lab in chapter 3 and I get this error when testing the web application (page 68):

```root@tfvm:~/Labs/docker-labs/application_server# node index.js 
/root/Labs/docker-labs/application_server/node_modules/mongodb/lib/mongo_client.js:257
    throw new TypeError('`connect` only accepts a callback');
    ^

TypeError: `connect` only accepts a callback
    at MongoClient.connect (/root/Labs/docker-labs/application_server/node_modules/mongodb/lib/mongo_client.js:257:11)
    at loadWordsFromDatabase (/root/Labs/docker-labs/application_server/index.js:21:19)
    at Object.<anonymous> (/root/Labs/docker-labs/application_server/index.js:50:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

What would be the reason for this ?

**Comment by sgnn7** [comment]
@archmangler Sorry for the delay - I was a bit busy lately.

As for that error, `mongodb` has released a major update to their API (v2.x.x -> v3.x.x) but in that changeover, it has moved the `connect` call to a different object. If the output of this command shows v3, this is the cause of your problem:
```
npm list mongodb mongodb-core
```
For the best fix, I [updated the code with this change](https://github.com/sgnn7/deploying_with_docker/commit/1deb5407fc462a03d587b29250386aad68169b1e) to support v3 that you can use instead.

If you want a quick fix, you can pin your mongodb version to the latest (but older) v2 version (`^2.2.34` at this time).To do the downgrade to v2, you can run ` npm install --save mongodb@^2.2.34` which will downgrade your package and update your `package.json`.

I will leave this issue open so that others may find it easier even though it has been fixed.
